const data = {
  // Sección: Propiedades y Técnicos Asignados[span_4](end_span)
  "propiedades": [
    { "id": 1, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Montevideo 14 &", "numero": "5036224", "tecnico": "Daniel Hitta", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 2, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Belloni", "numero": "5417384", "tecnico": "Daniel Hitta", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 3, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Libia", "numero": "5485266", "tecnico": "Daniel Hitta", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 4, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Colonia Nicolich (Alquiler)", "numero": "5013967", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 5, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Carrasco", "numero": "5034183", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 6, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Malvin &", "numero": "5036135", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 7, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Paso Carrasco", "numero": "5174732", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 8, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Montevideo 9", "numero": "5177049", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 9, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "San José De Carrasco", "numero": "5177634", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 10, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "El Bosque &", "numero": "5206634", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 11, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Camino Carrasco", "numero": "5527147", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 12, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Aeroparque", "numero": "5878659", "tecnico": "Daniel Hitta", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 13, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Ces [Campus] Montevideo Tres Cruces Institute", "numero": "5024769", "tecnico": "Javier Otaño", "dept_id": "0545601", "subcat": "ZCD" },
    { "id": 14, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Camp Deseret Recreation Camp", "numero": "5001715", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZKR" },
    { "id": 15, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Mis Uruguay Montevideo Mission Office (Malvin)", "numero": "5036135", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZMG" },
    { "id": 16, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Mis Uruguay Montevideo West Mission Office", "numero": "5077699", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZMG" },
    { "id": 17, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Centro De Servicios Montevideo", "numero": "5103614", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZA1" },
    { "id": 18, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Mis Uruguay Montevideo Mission Home", "numero": "5119766", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZMF" },
    { "id": 19, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Salinas", "numero": "5373778", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 20, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Mis Uruguay Montevideo West Mission Home", "numero": "5441544", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZMF" },
    { "id": 21, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "El Pinar", "numero": "5442389", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 22, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Lomas De Solymar", "numero": "5485495", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 23, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Parque Del Plata", "numero": "6008367", "tecnico": "Javier Otaño", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 24, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Fs Carmen (Futuro Sitio)", "numero": "5005341", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 25, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Carmen", "numero": "5013491", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 26, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Centro, Pueblo Nuevo &", "numero": "5034302", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 27, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Santa Lucia", "numero": "5036232", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 28, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Canelones", "numero": "5123593", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 29, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Asamblea, Estación &", "numero": "5130255", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 30, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "San José", "numero": "5196930", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 31, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Sarandi Grande", "numero": "5196949", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 32, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Sarandi Del Yi", "numero": "5197031", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 33, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Plaza", "numero": "5197104", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 34, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "San Ramón", "numero": "5373832", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 35, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Ferroviario, Piedra Alta", "numero": "5417317", "tecnico": "Jonny Pedreira", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 36, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Las Piedras", "numero": "5034671", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 37, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Pando", "numero": "5121728", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 38, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Montevideo 13 &", "numero": "5155924", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 39, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Obelisco & (Las Piedras)", "numero": "5172284", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 40, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Progreso", "numero": "5177626", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 41, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Bella Italia", "numero": "5210569", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 42, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Los Ceibos", "numero": "5210798", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 43, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "La Paz", "numero": "5210844", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 44, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Dieciocho De Mayo", "numero": "5295785", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 45, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Toledo", "numero": "5417368", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 46, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Prosperidad (En Desuso)", "numero": "5417376", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 47, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Villa Colon", "numero": "5417570", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 48, "pais": "Uruguay", "grupo": "Uruguay Centro", "nombre": "Colon, Ferrocarril", "numero": "5485541", "tecnico": "Luis Lizarraga", "dept_id": "0545601", "subcat": "ZFA" },
    { "id": 49, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Lussich", "numero": "5210577", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 50, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "La Paloma (Alquiler)", "numero": "5014873", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 51, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "VI Campo Rocha", "numero": "5021218", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 52, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "La Barra (Alquiler)", "numero": "5024161", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 53, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "La Capuera (Alquiler)", "numero": "5024884", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 54, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "La Paloma (Nuevo Alquiler)", "numero": "5025147", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 55, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Maldonado Centro &", "numero": "5034779", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 56, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Minas 1 (En Desuso)", "numero": "5035058", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 57, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Rocha", "numero": "5036283", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 58, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Piriapolis", "numero": "5136008", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 59, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "San Carlos", "numero": "5178681", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 60, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Maldonado Nuevo", "numero": "5210402", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 61, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Minas", "numero": "5210674", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" },
    { "id": 62, "pais": "Uruguay", "grupo": "Uruguay Este", "nombre": "Pan De Azucar, La Capuera", "numero": "6008364", "tecnico": "Mario Rivero", "dept_id": "0545602", "subcat": "ZFA" }
  ],
  
 "codigos_contabilidad": {
    "Limpieza_y_Suministros": [
      { "recurrente": "965", "materiales": "5864", "cuenta": "5864", "tipo": "Consumibles /Suministros de limpieza", "explicacion": "Costes para suministrar materiales y equipos de limpieza", "ejemplos": "productos químicos, productos de papel, herramientas no eléctricas, aspiradoras, etc." },
      { "recurrente": "166", "materiales": "960", "cuenta": "6865", "tipo": "Limpieza de la limpieza/Limpieza de proyectos", "explicacion": "Todos los proyectos de limpieza", "ejemplos": "mantenimiento recurrente, bajo demanda, limpieza de Mission Home, piscinas, etc." }
    ],
    "Mantenimiento_y_Reparacion": [
      { "recurrente": "167", "materiales": "967", "cuenta": "5866", "tipo": "Cerradura, llave y herrajes", "ejemplos": "Puertas interiores/exteriores, herrajes, llaves/FOB, puertas de separación." },
      { "recurrente": null, "materiales": "968", "cuenta": "5860", "tipo": "Eléctrico", "ejemplos": "Todo el trabajo eléctrico interior y exterior." },
      { "recurrente": "169", "materiales": "969", "cuenta": "6866", "tipo": "Ascensores", "ejemplos": "Reparaciones, mantenimiento e inspecciones de ascensores o plataformas." },
      { "recurrente": null, "materiales": "970", "cuenta": "5700", "tipo": "Mobiliario y Equipamiento", "ejemplos": "Televisores, ordenadores, impresoras, sofás, sillas, mesas." },
      { "recurrente": "171", "materiales": "971", "cuenta": "5866", "tipo": "HVACR", "ejemplos": "Gastos relacionados con HVAC y calderas (reparaciones e inspecciones)." },
      { "recurrente": null, "materiales": "972", "cuenta": "5806", "tipo": "TI (Tecnología de Internet)", "ejemplos": "WAP, switches, reparaciones de internet." },
      { "recurrente": null, "materiales": "973", "cuenta": "5860", "tipo": "Iluminación", "ejemplos": "Interruptores, balastos, bombillas, luminarias." },
      { "recurrente": "174", "materiales": "974/975", "cuenta": "6866/5866", "tipo": "Música y Sonido / Pintura", "ejemplos": "Equipos de sonido, micrófonos, pintura interior/exterior." },
      { "recurrente": "176", "materiales": "976", "cuenta": "5866", "tipo": "Plomería", "ejemplos": "Todo el trabajo de plomería interior y exterior." },
      { "recurrente": null, "materiales": "977", "cuenta": "5806", "tipo": "Reparaciones varias", "ejemplos": "Traslado de muebles existentes y otras reparaciones no categorizadas." },
      { "recurrente": null, "materiales": "978", "cuenta": "5866", "tipo": "Estructura Cubiertas", "ejemplos": "Reparaciones de estructura interior/exterior o del tejado." },
      { "recurrente": "179", "materiales": "979", "cuenta": "5866", "tipo": "Muestreo de agua", "ejemplos": "Mantenimiento e inspecciones regulatorias de agua." },
      { "recurrente": "180", "materiales": "980", "cuenta": "5806", "tipo": "Suelo", "ejemplos": "Suelos de madera, sintética o alfombra." },
      { "recurrente": "185", "materiales": "985", "cuenta": "5860", "tipo": "Inspecciones de Edificios", "ejemplos": "Inspecciones regulatorias realizadas por FM o técnicos externos." },
      { "recurrente": "186", "materiales": "986", "cuenta": "6866", "tipo": "Seguridad contra incendios/vida", "ejemplos": "Alarmas, detectores de humo, CO2, dispositivos DEA." },
      { "recurrente": "187", "materiales": "987", "cuenta": "5866", "tipo": "Seguridad", "ejemplos": "Sistemas de seguridad y personal." }
    ],
    "Jardineria_y_Jardines": [
      { "recurrente": "181", "materiales": "981", "cuenta": "5806", "tipo": "Terrenos/Mantenimiento", "ejemplos": "Jardinería, riego y árboles." },
      { "recurrente": "182", "materiales": "982", "cuenta": "5866", "tipo": "Superficies duras exteriores", "ejemplos": "Rectificado, sello de grieta, rayado." },
      { "recurrente": "183", "materiales": "983", "cuenta": "5866", "tipo": "Control de plagas", "ejemplos": "Insectos, animales pequeños." },
      { "recurrente": "184", "materiales": "984", "cuenta": "5866", "tipo": "Snow Removal", "ejemplos": "Retirada de nieve y hielo." }
    ],
    "Servicios_Publicos_y_Telecomunicaciones": [
      { "cat": "461", "cuenta": "5869", "tipo": "Electricidad" },
      { "cat": "462", "cuenta": "5870", "tipo": "Gas Natural" },
      { "cat": "463", "cuenta": "5870", "tipo": "Gasóleo de calefacción" },
      { "cat": "464", "cuenta": "5870", "tipo": "Propano" },
      { "cat": "465", "cuenta": "5870", "tipo": "Carbón" },
      { "cat": "466", "cuenta": "5872", "tipo": "Agua/Alcantarillado" },
      { "cat": "467", "cuenta": "15872", "tipo": "Solo agua" },
      { "cat": "468", "cuenta": "5672", "tipo": "Solo alcantarillado" },
      { "cat": "469", "cuenta": "5871", "tipo": "Residuos, Basura y Reciclaje" },
      { "cat": "470", "cuenta": "5872", "tipo": "Drenajes pluviales" },
      { "cat": "471", "cuenta": "5868", "tipo": "Utilidades múltiples diversas" },
      { "cat": "472", "cuenta": "5874", "tipo": "Costo telefónico unitario local" },
      { "cat": "527", "cuenta": "5674", "tipo": "Tarifas Continuas de Telecomunicaciones" }
    ],
    "Gastos_Operativos_Fijos_Otros": [
      { "cat": "449/479", "cuenta": "5862/5800", "tipo": "Alquileres domingos / Áreas comunes" },
      { "cat": "482", "cuenta": "5862", "tipo": "Alquiler instalaciones largo plazo" },
      { "cat": "489", "cuenta": "5862", "tipo": "Alquileres únicos (conferencias, bautizos)" },
      { "cat": "225", "cuenta": "5860", "tipo": "Puesta en Marcha Edificios Nuevos" },
      { "cat": "248", "cuenta": "5866", "tipo": "Consultor de RAI" },
      { "cat": "481", "cuenta": "5500", "tipo": "Dedicación puertas abiertas templo" },
      { "cat": "487", "cuenta": "5480", "tipo": "Permisos comerciales, licencias, tasas" },
      { "cat": "498", "cuenta": "5880", "tipo": "Compra local de unidades" },
      { "cat": "609", "cuenta": "1925", "tipo": "Depósitos de garantía" }
    ],
    "Costos_Administrativos": [
      { "cat": "510", "cuenta": "6100", "tipo": "Viajes cotidianos" },
      { "cat": "511", "cuenta": "6170", "tipo": "Operaciones de vehículos (gasolina, limpieza)" },
      { "cat": "512", "cuenta": "5400", "tipo": "Reuniones o formaciones FMG internas" },
      { "cat": "514", "cuenta": "5772", "tipo": "Mantenimiento y reparación de vehículos" },
      { "cat": "515", "cuenta": "5480", "tipo": "Impuestos sobre vehículos y matrícula" },
      { "cat": "516", "cuenta": "6109", "tipo": "Viajes-Conferencias y seminarios" },
      { "cat": "518", "cuenta": "5104", "tipo": "Reembolso de kilometraje" },
      { "cat": "521", "cuenta": "5200", "tipo": "Suministros y gastos de oficina FM" },
      { "cat": "523", "cuenta": "5370", "tipo": "Gastos de móviles/buscapersonas" },
      { "cat": "524", "cuenta": "5379", "tipo": "Franqueo/Envío" },
      { "cat": "526", "cuenta": "5777", "tipo": "Reparaciones de ordenadores" },
      { "cat": "528", "cuenta": "5700", "tipo": "Mobiliario y equipamiento oficina FM" },
      { "cat": "540", "cuenta": "5866", "tipo": "Administrador contratado" }
    ]
  },

  // Sección: Centros de Costos Uruguay[span_12](end_span)
  "centros_costos_uruguay": [
    { "categoria": "GPG", "grupo": "Uruguay Centro", "dept_id": "0545601", "administrador": "Eduardo Rios" },
    { "categoria": "GPG", "grupo": "Uruguay Este", "dept_id": "0545602", "administrador": "David Sandes" },
    { "categoria": "GPG", "grupo": "Uruguay Oeste", "dept_id": "0545603", "administrador": "Daniel Chiesa" },
    { "categoria": "GPG", "grupo": "Uruguay Norte", "dept_id": "0545604", "administrador": "Kevin Rodriguez" },
    { "categoria": "GMG", "grupo": "Centro-Este", "dept_id": "0545641", "administrador": "Pablo Altano" },
    { "categoria": "GMG", "grupo": "Oeste-Norte", "dept_id": "0545642", "administrador": "Daniel Saavedra" },
    { "categoria": "Soporte", "grupo": "Uruguay", "dept_id": "0545675", "administrador": "Gonzalo Silveira" }
  ]
};

export default data;
